/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as DataStructuresRouteImport } from './routes/data-structures'
import { Route as ComplexityRouteImport } from './routes/complexity'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as AlgorithmsRouteImport } from './routes/algorithms'
import { Route as IndexRouteImport } from './routes/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStructuresRoute = DataStructuresRouteImport.update({
  id: '/data-structures',
  path: '/data-structures',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexityRoute = ComplexityRouteImport.update({
  id: '/complexity',
  path: '/complexity',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/data-structures': typeof DataStructuresRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/data-structures': typeof DataStructuresRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/data-structures': typeof DataStructuresRoute
  '/glossary': typeof GlossaryRoute
  '/interview': typeof InterviewRoute
  '/quiz': typeof QuizRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithms'
    | '/comparison'
    | '/complexity'
    | '/data-structures'
    | '/glossary'
    | '/interview'
    | '/quiz'
    | '/roadmap'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithms'
    | '/comparison'
    | '/complexity'
    | '/data-structures'
    | '/glossary'
    | '/interview'
    | '/quiz'
    | '/roadmap'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/algorithms'
    | '/comparison'
    | '/complexity'
    | '/data-structures'
    | '/glossary'
    | '/interview'
    | '/quiz'
    | '/roadmap'
    | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsRoute: typeof AlgorithmsRoute
  ComparisonRoute: typeof ComparisonRoute
  ComplexityRoute: typeof ComplexityRoute
  DataStructuresRoute: typeof DataStructuresRoute
  GlossaryRoute: typeof GlossaryRoute
  InterviewRoute: typeof InterviewRoute
  QuizRoute: typeof QuizRoute
  RoadmapRoute: typeof RoadmapRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-structures': {
      id: '/data-structures'
      path: '/data-structures'
      fullPath: '/data-structures'
      preLoaderRoute: typeof DataStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity': {
      id: '/complexity'
      path: '/complexity'
      fullPath: '/complexity'
      preLoaderRoute: typeof ComplexityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms': {
      id: '/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsRoute: AlgorithmsRoute,
  ComparisonRoute: ComparisonRoute,
  ComplexityRoute: ComplexityRoute,
  DataStructuresRoute: DataStructuresRoute,
  GlossaryRoute: GlossaryRoute,
  InterviewRoute: InterviewRoute,
  QuizRoute: QuizRoute,
  RoadmapRoute: RoadmapRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
